[package]
name = "lesson6"
version = "1.0.0"
authors = []

[addresses]
MyPackage="0x1"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
